# Use root/example as user/password credentials
version: '3.1'

volumes:
  pgdata:
    
services:
  postgres:
    container_name: postgres
    image: ghcr.io/onos9/onos9/postgres:latest
    restart: unless-stopped
    ports:
      - 5406:5432
    environment:
      POSTGRES_USER: cavelms
      POSTGRES_PASSWORD: 1414{bruno}
      POSTGRES_DB: cavelms
    volumes: 
      - pgdata:/var/lib/postgresql/data
      
  php-fpm:
    container_name: cavesite
    image: ghcr.io/onos9/cavesite:latest
    restart: unless-stopped
    pull_policy: always
    ports:
      - 9000
